version: '3'

services:
  site:
    container_name: code-fracz-com
    build: .
    restart: unless-stopped
    networks: [proxy]
    environment:
      VIRTUAL_HOST: code.fracz.com,www.code.fracz.com
      LETSENCRYPT_HOST: code.fracz.com,www.code.fracz.com
      LETSENCRYPT_EMAIL: fraczwojciech@gmail.com
    expose: [80]
    volumes:
      - ../:/var/www:z
      - ./apache-conf:/etc/apache2/sites-available:z

networks:
  proxy:
    external:
      name: webproxy